config/routes.rb
Rails.application.routes.draw do
  resources :movies
  get 'home/about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: %i[ show edit update destroy ]

  # GET /movies or /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1 or /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies or /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: "Movie was successfully created." }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1 or /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: "Movie was successfully updated." }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1 or /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: "Movie was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def movie_params
      params.require(:movie).permit(:name, :language, :rating)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/home/_alerts.html.erb
<div class="alert alert-primary" role="alert">
<p id="notice"><%= notice %></p> 
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Movies App</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Movies", movies_path, class:"nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "About Us", home_about_path , class:"nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About..<h1>

app/views/home/index.html.erb
<h1>Hello</h1>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

   <title>Movies</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

   <%= render 'home/header' %>
     <% if notice %>
   <%= render 'home/alerts' %>
   <% end %>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
  </body>
</html>

app/views/movies/_form.html.erb
<div style="margin:50px"> 
<%= form_with(model: movie) do |form| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
        <% movie.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group col-lg-3">
    <%= form.text_field :name ,class:"form-control" ,placeholder:"Name" %>
  </div>
  <br>
  <div class="field form-group col-lg-3">
    <%= form.text_field :language ,class:"form-control"  ,placeholder:"Language"%>
  </div>
  <br>
  <div class="field form-group col-lg-3">
    <%= form.number_field :rating ,class:"form-control" ,placeholder:"Rating" %>
  </div>
  <br>
  <div class="actions">
    <%= form.submit class:"btn btn-secondary"%>
  </div>
<% end %>
</div>

app/views/movies/edit.html.erb
<div style="margin:50px">
<h1>Editing Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Show', @movie ,class:"btn btn-secondary"%>
<%= link_to 'Back', movies_path,class:"btn btn-dark" %>

</div>

app/views/movies/index.html.erb
<div style="margin:30px">


<h1>Movies</h1>

<table class="table table-striped table-hover table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Language</th>
      <th>Rating</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.name %></td>
        <td><%= movie.language %></td>
        <td><%= movie.rating %></td>
        <td><%= link_to 'Show', movie, class:"btn btn-outline-primary" %></td>
        <td><%= link_to 'Edit', edit_movie_path(movie), class:"btn btn-outline-success"  %></td>
        <td><%= link_to 'Delete', movie, method: :delete, data: { confirm: 'Are you sure?' } , class:"btn btn-outline-danger"  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add Movie', new_movie_path,class:"btn btn-outline-primary" %>
</div>

app/views/movies/new.html.erb
<div style="margin-left:20px">
<h1 >New Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Back', movies_path,class:"btn btn-dark" %>
</div>

app/views/movies/show.html.erb
<div style=margin:20px>
 <div class="p-5 mb-4 bg-light rounded-3">
      <div class="container-fluid py-5">
        <h1 class="display-5 fw-bold"><%= @movie.name %></h1>
        <p class="col-md-8 fs-4">Rating:<%= @movie.rating %> </p>
         <p class="col-md-8 fs-4">Language:<%= @movie.language %> </p>
         <%= link_to 'Edit', edit_movie_path(@movie), class:"btn btn-outline-success" %> 
          <%= link_to 'Back', movies_path, class:"btn btn-outline-danger" %>
      </div>
    </div>
</div>